### ISSUE TITLE
Query regarding the source of commands used in the drivers

### ISSUE THREAD

**Issue by asgv123** [rock-drivers/drivers-sonar_tritech#8]
Hi!
I am a member of the software sub-division of AUV-IITB, a tech team at IIT Bombay. We are currently working on integrating a sonar - Tritech Super SeaKing - into our system, which primarily runs on Ubuntu.

We have been unable to locate any resource to help us write drivers for the same in Ubuntu. Can you please provide some library or documentation to help us?
If not, can you at least provide the sources used to write the commands and obtain the libraries used in your code for Sea Micron and SeaNetProfiling.

Any help is appreciated.

Thanks
Andrews GV
Software Trainee
AUV-IITB

**Comment by doudou** [comment]
I don't know where the documentation is, or if there ever was a documentation. You could use this library as a basis (or as-is, actually).

**Comment by asgv123** [comment]
Ok... Thanks a lot!
